### ISSUE TITLE
Expression error I guess

### ISSUE THREAD

**Issue by farwl** [ShaneBeee/Sk-Perm#5]
```[13:17:14] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[13:17:14] [Server thread/ERROR]: #!#! 
[13:17:14] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[13:17:14] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:17:14] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:17:14] [Server thread/ERROR]: #!#! Here is full list of them:
[13:17:14] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SkQuery 
[13:17:14] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:17:14] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:17:14] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:17:14] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:17:14] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:17:14] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:17:14] [Server thread/ERROR]: #!#! 
[13:17:14] [Server thread/ERROR]: #!#! Stack trace:
[13:17:14] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[13:17:14] [Server thread/ERROR]: #!#!     at tk.shanebee.**skperm**.utils.api.LuckAPI.getPlayerPrefix(LuckAPI.java:430)
[13:17:14] [Server thread/ERROR]: #!#!     at tk.shanebee.skperm.permPlugins.elements.expressions.ExprPlayerPrefixSuffix.get(ExprPlayerPrefixSuffix.java:62)
[13:17:14] [Server thread/ERROR]: #!#!     at tk.shanebee.skperm.permPlugins.elements.expressions.ExprPlayerPrefixSuffix.get(ExprPlayerPrefixSuffix.java:21)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:459)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:623)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:90)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)
[13:17:14] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:17:14] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520)
[13:17:14] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.dispatchCommand(Skript.java:1314)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:84)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:96)
[13:17:14] [Server thread/ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:110)
[13:17:14] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[13:17:14] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[13:17:14] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008)
[13:17:14] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[13:17:14] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956)
[13:17:14] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801)
[13:17:14] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[13:17:14] [Server thread/ERROR]: #!#! 
[13:17:14] [Server thread/ERROR]: #!#! Version Information:
[13:17:14] [Server thread/ERROR]: #!#!   Skript: 2.4-alpha1 (custom version)
[13:17:14] [Server thread/ERROR]: #!#!     Flavor: selfbuilt-unknown
[13:17:14] [Server thread/ERROR]: #!#!     Date: unknown
[13:17:14] [Server thread/ERROR]: #!#!   Bukkit: 1.14.2-R0.1-SNAPSHOT
[13:17:14] [Server thread/ERROR]: #!#!   Minecraft: 1.14.2
[13:17:14] [Server thread/ERROR]: #!#!   Java: 1.8.0_191 (OpenJDK 64-Bit Server VM 25.191-b12)
[13:17:14] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.15.0-1039-aws
[13:17:14] [Server thread/ERROR]: #!#! 
[13:17:14] [Server thread/ERROR]: #!#! Server platform: Spigot
[13:17:14] [Server thread/ERROR]: #!#! 
[13:17:14] [Server thread/ERROR]: #!#! Current node: null
[13:17:14] [Server thread/ERROR]: #!#! Current item: send "Your group's prefix: %Prefix  of player {_g}(as org.bukkit.OfflinePlayer)%" to event-player/console
[13:17:14] [Server thread/ERROR]: #!#! Current trigger: command (command) (luxperms.sk, line 226)
[13:17:14] [Server thread/ERROR]: #!#! 
[13:17:14] [Server thread/ERROR]: #!#! Thread: Server thread
[13:17:14] [Server thread/ERROR]: #!#! 
[13:17:14] [Server thread/ERROR]: #!#! Language: english
[13:17:14] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[13:17:14] [Server thread/ERROR]: #!#! 
[13:17:14] [Server thread/ERROR]: #!#! End of Error.
[13:17:14] [Server thread/ERROR]: #!#! ```

Basicly, I had a send effect in my skript code and it was going to send a group's prefix, but nothing happened. I checked logs, and found this.

**Comment by ShaneBeee** [comment]
what is the code you were using that caused this error?

**Comment by farwl** [comment]
command:
	command = "abc":
		set {_g} to player's group
		send "Your group's prefix: %{_g}'s perm prefix%"
		send "Your group's prefix: %perm prefix of group {_g}%"
		send "Your group's prefix: %group {_g}'s perm prefix%"

**Comment by ShaneBeee** [comment]
this error is caused from this line
```
send "Your group's prefix: %{_g}'s perm prefix%"
```
And that is because that syntax is for getting a player's perm prefix not a group's perm prefix

The correct syntaxes for group's prefix:
```
[the] [perm[ission]] (prefix|suffix) of group %string% [in [world] %world%] 
group %string%'s [the] [perm[ission]] (prefix|suffix) [in [world] %world%] 
```

**Comment by farwl** [comment]
ahem

![skperm_prefix_error](https://user-images.githubusercontent.com/44182379/59301842-8b1a0c80-8c60-11e9-8d15-e3442a2283bb.PNG)

![image](https://user-images.githubusercontent.com/44182379/59301833-85bcc200-8c60-11e9-9c63-1522900f374b.png)

**Comment by ShaneBeee** [comment]
try add `perm` like `perm prefix`

**Comment by Farwl** [comment]
Wait I just saw this 
![image](https://user-images.githubusercontent.com/44182379/59301975-dfbd8780-8c60-11e9-85b1-39b0ba31b927.png)

**Comment by farwl** [comment]
Oh that worked. tysm

**Comment by farwl** [comment]
Alright I'll stop bothering you now. Thanks for all the help dude.

**Comment by ShaneBeee** [comment]
> Oh that worked. tysm

You're welcome :)
