### ISSUE TITLE
Problem with the latest Sk-Perm

### ISSUE THREAD

**Issue by iOussama** [ShaneBeee/Sk-Perm#7]
I'm trying to download SK-Perm but I get these errors..
```[17:35:32` INFO]: [Sk-Perm] Enabling Sk-Perm v2.3.0*
[17:35:32 WARN]: [Sk-Perm] Loaded class ch.njol.skript.Skript from Skript v2.5.3 which is not a depend, softdepend or loadbefore of this plugin.
[17:35:32 INFO]: [Sk-Perm] [Skript] Dependency found, loading Skript syntaxes
[17:35:32 INFO]: [Sk-Perm] [Vault] Dependency found, Vault syntaxes loaded
[17:35:32 ERROR]: Error occurred while enabling Sk-Perm v2.3.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
        at tk.shanebee.skperm.utils.api.LuckAPI.<init>(LuckAPI.java:17) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?]
        at java.lang.Class.newInstance(Class.java:642) ~[?:?]
        at tk.shanebee.skperm.SkPerm.loadApi(SkPerm.java:88) ~[?:?]
        at tk.shanebee.skperm.SkPerm.onEnable(SkPerm.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paper.jar:git-Paper-777]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper.jar:git-Paper-777]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[paper.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[paper.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[paper.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[paper.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[paper.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[paper.jar:git-Paper-777]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper.jar:git-Paper-777]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[paper.jar:git-Paper-777]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 20 more
[17:35:32 INFO]: [Sk-Perm] Disabling Sk-Perm v2.3.0
[17:35:32 INFO]: [Sk-Perm] Unloaded successfully```

**Comment by ShaneBeee** [comment]
Luckperms is no longer supported

<img width="1534" alt="Screen Shot 2021-06-19 at 10 36 26 AM" src="https://user-images.githubusercontent.com/20008482/122650908-46949780-d0ea-11eb-99a4-65d6ee8f75c7.png">
